version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    build: .
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    command: python manage.py runserver 0.0.0.0:8000 --settings=docker_geonode.settings
    env_file:
      - ./scripts/docker/env/production/django.env

  celery:
    build: .
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=docker_geonode.celery_app:app -B -l INFO
    env_file:
      - ./scripts/docker/env/production/django.env

  qgisserver:
    image: senoadiw/qgis-server
    #hostname: qgis-server
    #volumes:
    #  - ./gis:/gis
    # ports:
    # - "8080:80"
    #links:
    #  - db:db

  geonode:
    image: geonode/nginx
    links:
      - django
    ports:
      - "80:80"
