version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    build: .
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=docker_geonode.settings
      - SITEURL=http://192.168.99.100/
      - QGIS_SERVER_URL=http://qgisserver/
      - ALLOWED_HOSTS=['*',]

  celery:
    build: .
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=docker_geonode.celery_app:app -B -l INFO
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=docker_geonode.settings
      - QGIS_SERVER_URL=http://qgisserver/
      - ALLOWED_HOSTS=['django',]
      - C_FORCE_ROOT=1

  qgisserver:
    image: senoadiw/qgis-server
    #hostname: qgis-server
    #volumes:
    #  - ./gis:/gis
    # ports:
    # - "8080:80"
    #links:
    #  - db:db

  nginx:
    image: terranodo/nginx
    links:
      - django
    ports:
      - "80:80"
